

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    depends_on:
      - frontend

    volumes:
      - zap_data:/zap/wrk:rw
    command: >
      zap-baseline.py
      -t http://frontend:80
      -J
      
    

volumes:
  zap_data:
    # This volume is used to persist ZAP data across runs
    # It can be useful for debugging or for running multiple scans
    # without losing previous results.