name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend
      run: docker build -t frontend-test ./frontend

    - name: Build backend
      run: docker build -t backend-test ./backend

    - name: Lint Dockerfiles (optional)
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: ./frontend/Dockerfile

    # Optional: Run docker-compose
    - name: Spin up services (docker-compose)
      run: docker-compose up -d --build

    - name: Wait for services
      run: sleep 15

    - name: Check containers running
      run: docker ps -a

    # Optional: Run Tests if available
    # - name: Run backend tests
    #   run: docker exec <backend-container-name> npm test
